In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Dropout,Bidirectional

In [3]:
data = pd.read_csv("/content/Google_Stock_Price_Test.csv")

In [4]:
data

         Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

In [33]:
#Prepare the data
## Extract the 'Close' column

# Extract the closing prices
prices = data['Close'].values.reshape(-1, 1)

# Scale the prices between 0 and 1
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_prices = scaler.fit_transform(prices)

In [35]:
# Determine the training and testing data sizes
train_size = int(len(scaled_prices) * 0.8)
test_size = len(scaled_prices) - train_size

# Split the data into training and testing sets
train_data = scaled_prices[:train_size, :]
test_data = scaled_prices[train_size:, :]

In [36]:
# Create sequences for training
def create_sequences(data, sequence_length):
    x = []
    y = []
    for i in range(len(data) - sequence_length):
        x.append(data[i:i+sequence_length])
        y.append(data[i+sequence_length])
    return np.array(x), np.array(y)

sequence_length = 10  # Number of previous prices to consider
train_x, train_y = create_sequences(train_data, sequence_length)
test_x, test_y = create_sequences(test_data, sequence_length)

In [37]:
# Create sequences for training
def create_sequences(data, sequence_length):
    x = []
    y = []
    for i in range(len(data) - sequence_length):
        x.append(data[i:i+sequence_length])
        y.append(data[i+sequence_length])
    return np.array(x), np.array(y)

sequence_length = 10  # Number of previous prices to consider
train_x, train_y = create_sequences(train_data, sequence_length)
test_x, test_y = create_sequences(test_data, sequence_length)

In [38]:
#Create the RNN model
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(sequence_length, 1)))
model.add(LSTM(units=50))
model.add(Dense(units=1))

model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(train_x, train_y, epochs=100, batch_size=32)

Epoch 1/100
1/1 [==============================] - 6s 6s/step - loss: 0.4044
Epoch 2/100
1/1 [==============================] - 0s 21ms/step - loss: 0.3594
Epoch 3/100
1/1 [==============================] - 0s 22ms/step - loss: 0.3176
Epoch 4/100
1/1 [==============================] - 0s 20ms/step - loss: 0.2784
Epoch 5/100
1/1 [==============================] - 0s 22ms/step - loss: 0.2413
Epoch 6/100
1/1 [==============================] - 0s 23ms/step - loss: 0.2061
Epoch 7/100
1/1 [==============================] - 0s 19ms/step - loss: 0.1725
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 0.1407
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 0.1111
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0847
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0629
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 0.0478
Epoch 13/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0419
Epoch 14/100
1/1 [==============================] - 0s 19ms/step - loss: 0.0465
Epoch 15/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0591
Epoch 16/100
1/1 [==============================] - 0s 26ms/step - loss: 0.0716
Epoch 17/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0769
Epoch 18/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0740
Epoch 19/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0661
Epoch 20/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0571
Epoch 21/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0495
Epoch 22/100
1/1 [==============================] - 0s 28ms/step - loss: 0.0447
Epoch 23/100
1/1 [==============================] - 0s 19ms/step - loss: 0.0426
Epoch 24/100
1/1 [==============================] - 0s 24ms/step - loss: 0.0428
Epoch 25/100
1/1 [==============================] - 0s 26ms/step - loss: 0.0443
Epoch 26/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0464
Epoch 27/100
1/1 [==============================] - 0s 24ms/step - loss: 0.0484
Epoch 28/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0500
Epoch 29/100
1/1 [==============================] - 0s 19ms/step - loss: 0.0509
Epoch 30/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0510
Epoch 31/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0504
Epoch 32/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0493
Epoch 33/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0477
Epoch 34/100
1/1 [==============================] - 0s 19ms/step - loss: 0.0461
Epoch 35/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0445
Epoch 36/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0432
Epoch 37/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0424
Epoch 38/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0420
Epoch 39/100
1/1 [==============================] - 0s 24ms/step - loss: 0.0422
Epoch 40/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0426
Epoch 41/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0432
Epoch 42/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0436
Epoch 43/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0438
Epoch 44/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0437
Epoch 45/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0433
Epoch 46/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0427
Epoch 47/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0420
Epoch 48/100
1/1 [==============================] - 0s 27ms/step - loss: 0.0415
Epoch 49/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0411
Epoch 50/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0409
Epoch 51/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0409
Epoch 52/100
1/1 [==============================] - 0s 26ms/step - loss: 0.0409
Epoch 53/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0410
Epoch 54/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0410
Epoch 55/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0410
Epoch 56/100
1/1 [==============================] - 0s 27ms/step - loss: 0.0408
Epoch 57/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0406
Epoch 58/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0403
Epoch 59/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0400
Epoch 60/100
1/1 [==============================] - 0s 27ms/step - loss: 0.0397
Epoch 61/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0394
Epoch 62/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0392
Epoch 63/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0391
Epoch 64/100
1/1 [==============================] - 0s 24ms/step - loss: 0.0390
Epoch 65/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0389
Epoch 66/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0388
Epoch 67/100
1/1 [==============================] - 0s 27ms/step - loss: 0.0386
Epoch 68/100
1/1 [==============================] - 0s 27ms/step - loss: 0.0384
Epoch 69/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0381
Epoch 70/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0379
Epoch 71/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0376
Epoch 72/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0374
Epoch 73/100
1/1 [==============================] - 0s 35ms/step - loss: 0.0372
Epoch 74/100
1/1 [==============================] - 0s 24ms/step - loss: 0.0370
Epoch 75/100
1/1 [==============================] - 0s 29ms/step - loss: 0.0368
Epoch 76/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0366
Epoch 77/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0364
Epoch 78/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0362
Epoch 79/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0359
Epoch 80/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0357
Epoch 81/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0354
Epoch 82/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0351
Epoch 83/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0349
Epoch 84/100
1/1 [==============================] - 0s 26ms/step - loss: 0.0346
Epoch 85/100
1/1 [==============================] - 0s 28ms/step - loss: 0.0344
Epoch 86/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0341
Epoch 87/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0338
Epoch 88/100
1/1 [==============================] - 0s 20ms/step - loss: 0.0335
Epoch 89/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0332
Epoch 90/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0329
Epoch 91/100
1/1 [==============================] - 0s 22ms/step - loss: 0.0326
Epoch 92/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0322
Epoch 93/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0319
Epoch 94/100
1/1 [==============================] - 0s 25ms/step - loss: 0.0316
Epoch 95/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0313
Epoch 96/100
1/1 [==============================] - 0s 37ms/step - loss: 0.0309
Epoch 97/100
1/1 [==============================] - 0s 30ms/step - loss: 0.0306
Epoch 98/100
1/1 [==============================] - 0s 23ms/step - loss: 0.0302
Epoch 99/100
1/1 [==============================] - 0s 28ms/step - loss: 0.0299
Epoch 100/100
1/1 [==============================] - 0s 21ms/step - loss: 0.0295

In [43]:
# Evaluate the model
loss = model.evaluate(test_x, test_y)
print('Test Loss:', loss)

# Make predictions
predictions = model.predict()
predictions = scaler.inverse_transform(predictions)

NameError: ignored